### ISSUE TITLE
Importing nxviz fails in python 3.4.3

### ISSUE THREAD

**Issue by benelot** [ericmjl/nxviz#238]
* nxviz version: 0.3.4
* Python version: 3.4.3
* Operating System: Linux Mint Rosa (Ubuntu based)

### Description

I was trying to import nxviz, but I get an invalid syntax.

### What I Did

I installed nxviz using pip3 install nxviz, then tried to use it, but it fails to properly import. I am not sure why it fails, a similar mistake only happened to someone else when using python 2.7.

   import sys
    print(sys.version)
    ## network graphs
    import networkx as nx
    import nxviz as nv

Output:

    3.4.3 (default, Nov 28 2017, 16:41:13) 
    [GCC 4.8.4]
    Traceback (most recent call last):

      File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2910, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)

      File "<ipython-input-36-373cb9dec556>", line 34, in <module>
        import nxviz as nv

      File "/usr/local/lib/python3.4/dist-packages/nxviz/__init__.py", line 1, in <module>
        from nxviz.plots import ArcPlot, CircosPlot, MatrixPlot  # NOQA

      File "/usr/local/lib/python3.4/dist-packages/nxviz/plots.py", line 294
        patch = patches.PathPatch(path, lw=1, **self.edgeprops, zorder=1)
                                                              ^
    SyntaxError: invalid syntax

Any idea what could be wrong?

**Comment by ericmjl** [comment]
Ah, I had to look this up a bit - I take advantage of Python 3.5's `**` syntax to do dictionary unpacking. Do you have to use Python 3.4, or is it possible to create a project-specific environment that uses Python 3.6? I believe I also use Python 3.6's f-strings in multiple places in the codebase,
 for convenience when printing error messages.

**Comment by ericmjl** [comment]
Thank you! Also, if there's ways the library could be improved (e.g. some people have asked about labels on nodes), do let me know via the issue tracker!
