### ISSUE TITLE
Scaling plots

### ISSUE THREAD

**Issue by benelot** [ericmjl/nxviz#239]
Hi,

Maybe I am overseeing something, but I can not find out how to scale my network graphs to a different size than the standard size. How do I make it bigger?

**Comment by ericmjl** [comment]
I’m away from my computer right now, but I’ll see what I can do from my phone here. When you say scaling, with, say, Circos plots as an example, it can take multiple meanings. Do you mean:

- increasing radius of the plot, thereby also increasing the distance between nodes?
- increasing the DPI of the plot, thereby proportionally increasing the size of everything on the screen?
- increasing the size of each node circle, thereby increasing the size of the plot as a whole?

**Comment by benelot** [comment]
Sorry, I meant the DPI, which really means that I want a larger picture in
the output. The images I get are always super small.

**Comment by ericmjl** [comment]
No worries! Under the hood, nxviz is using matplotlib to do the drawing. It looks like I should make the figure size an option.m that can be passed in, with a default of (6, 6). Give me the evening, this looks like a small fix + minor version bump.

**Comment by ericmjl** [comment]
Ok, I just pushed a patch to master, super thankful for WiFi hotspot capabilities on Simple Mobile! Now you can do something like:

```
c = nv.CircosPlot(G, figsize=(9, 9))  # specify figure size, in inches, using matplotlib conventions.
c.draw()
plt.show()
```

Are you comfortable installing from GitHub? I the syntax is something like `pip install git+https://github.com/ericmjl/nxviz.git`.

**Comment by benelot** [comment]
Wow, that is awesome! Yeah, I am comfortable with installing from Github. I
had the impression that it was impossible to change the figsize from
outside, thanks for changing that so quickly.

**Comment by ericmjl** [comment]
No worries. Do let me know how it goes. If it works for you, I’m cool pushing up a new release to PyPI and conda-forge.

**Comment by benelot** [comment]
Thanks for the change again, it works perfectly on my side.

**Comment by ericmjl** [comment]
Awesome stuff. Thanks for reporting! We all rely on each other to find out bugs and places for improvement, much appreciated!

**Comment by olanag1** [comment]
Hi, it seems that figsize option is no more available in new version. How can I scale the graph ? 
Thanks for youe help :)
