### ISSUE TITLE
AttributeError: no attribute 'groups'

### ISSUE THREAD

**Issue by zeneofa** [ericmjl/nxviz#306]
* nxviz version: 0.3.6
* Python version: 3.6
* Operating System: macosx

### Description

Running the examples in the git examples folder generates an attribute error, after a fresh install from the git repo. 

### What I Did

```
(test-nxviz) ╭─[~/git/nxviz/examples/circos]─[jq2@sweetgum]─[0]─[10891]
╰─[:)] % python barbell.py
Traceback (most recent call last):
  File "barbell.py", line 16, in <module>
    c.draw()
  File "/Users/jq2/miniconda/envs/test-nxviz/lib/python3.6/site-packages/nxviz/plots.py", line 182, in draw
    if self.groups:
AttributeError: 'CircosPlot' object has no attribute 'groups'

```

**Comment by ericmjl** [comment]
@zenofa thanks for reporting! I will triage this for a bug fix.

**Comment by ericmjl** [comment]
@zeneofa there is a quick way to check! Run the tests at the command line from nxviz's root directory:

```bash
$ py.test
```

**Comment by ThijsHrm** [comment]
In my upcoming pull request this is fixed as follows: 

> if hasattr(self, 'groups') and self.groups:

note that self.groups is only set if the parameter group_label_position is specified. This won't break anything

**Comment by ericmjl** [comment]
I believe this bug has been fixed. Closing.
