### ISSUE TITLE
Group label incorrectly positioned

### ISSUE THREAD

**Issue by zeneofa** [ericmjl/nxviz#307]
* nxviz version: 0.3.6
* Python version: 3.6
* Operating System: macosx

### Description
I have a larger network with group labels, I am trying to label and color the nodes by their respective groups in a Circos plot. When doing this for a network of 1000 nodes and 7 groups, the group labels are not positioned correctly. In particular this occurs when one group is much larger than the others. I would expect the labels (when group label "middle" is used) to appear adjacent to the respective group it is labelled for. 

### What I Did

```
import networkx as nx
import nxviz
import numpy as np
import matplotlib.pyplot as plt

G = nx.fast_gnp_random_graph(1000,0.001)
for n,d in G.nodes(data=True):
    a = np.random.uniform()
    if a < 0.70:
        G.node[n]['class'] = "Big"
    elif a < 0.75:
        G.node[n]['class'] = "tiny1"
    elif a < 0.80:
        G.node[n]['class'] = "tiny2"
    elif a < 0.85:
        G.node[n]['class'] = "tiny3"
    elif a < 0.90:
        G.node[n]['class'] = "tiny4"
    elif a < 0.95:
        G.node[n]['class'] = "tiny5"
    else:
        G.node[n]['class'] = "tiny6"

c = nxviz.plots.CircosPlot(G,
                           node_grouping='class',
                           node_color='class',
                           node_order='class',
                           node_labels=False,
                           group_label_position='middle',
                           group_label_color='class'
                           )

c.draw()
plt.show()
```

![randomgraphgrouplabels](https://user-images.githubusercontent.com/5684085/38216618-52344426-3699-11e8-9f0b-240032d66309.png)

**Comment by ericmjl** [comment]
Hi @zeneofa! Thanks for the post. I tried the code that you provided, but what I get in the end looks correct:

![figure_2](https://user-images.githubusercontent.com/2631566/38217090-f88d6ff4-369a-11e8-886f-38c29a6ee8d8.png)

At first glance, I'm not quite sure where things went wrong here. Perhaps software versions?

**Comment by zeneofa** [comment]
A complete re-install in a new environment worked. Have to try and determine what is causing the conflict. Thanks for the help though :).

**Comment by ericmjl** [comment]
My pleasure. Closing for now; feel free to reopen or post a new issue if it crops up again.
