### ISSUE TITLE
group not alphabetically

### ISSUE THREAD

**Issue by noragak** [ericmjl/nxviz#323]
Hi Eric,
recently I run into a problem regarding the grouping. By default the grouping is resorting the groups alphabetically. Wouldn't it be better to keep a certain oder or to have an option to control this order?
Thanks
Nora

**Comment by ericmjl** [comment]
@noragak thanks for pinging in! Let me check the source code to see where this is happening.

**Comment by ericmjl** [comment]
I see it's happening [here](https://github.com/ericmjl/nxviz/blob/master/nxviz/plots.py#L310). 

I see where you're coming from - the intent is to allow an end-user to specify the order of the groups rather than automatically do so. 

What do you think the API design should look like to enable this?

**Comment by noragak** [comment]
Difficult question! 

1) So one option would be again another parameter like "grouping_order" where one can choose between "alphabetically" and something like "default" (like a first come first serve order of the node annotations which later  build the groups). Also maybe different parameters. But that are the only ones I can think of right now...
2) But maybe there is an easier way?

**Comment by ericmjl** [comment]
> So one option would be again another parameter like "grouping_order" where one can choose between "alphabetically" and something like "default" (like a first come first serve order of the node annotations which later build the groups). Also maybe different parameters. But that are the only ones I can think of right now...

I think this is a great idea! Just have to make sure that `grouping_order` is right next to `node_grouping` in the docstrings, of course, otherwise it'll be easy to miss that one. :smile:.

**Comment by noragak** [comment]
Great. I'll start implementing it today. What other options should be added other than "alphabetically", "default"?

**Comment by ericmjl** [comment]
Thanks @noragak! I think those look good for now. Perhaps this might be one of those few places where having the user explicitly pass in a list is also a reasonable and good option. What do you think?

**Comment by noragak** [comment]
The implementation is done: you can have a look at it in my master branch. Right now you can distinguish between "alphabetically" (which is the default option to keep all plots created till now the same) and the other is "default" (maybe I should change the name here..?).

**Comment by ericmjl** [comment]
Woohoo!! Could you do a PR in? GitHub has some really nice features related to showing code diffs.

**Comment by ericmjl** [comment]
Seeing as how #325 was merged, I'm closing this issue for now.
