### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by zeneofa** [ericmjl/nxviz#328]
Hi,

I am on system where the only way that I can install nxviz using pip from a pypi mirror. The code on pypi doesn't have the group_label_position option for Circosplots. Is it possible to update the pypi code?

I have checked the pip install on other systems (not using the local pypi mirror) and the code is still different.

**Comment by ericmjl** [comment]
@zeneofa not a problem! I just cut a release, let me know if it works. If it doesn't, I'll try to debug and push another patched version up to pypi.

**Comment by zeneofa** [comment]
It worked thanks. :)
