### ISSUE TITLE
Value Error while trying to color the nodes in CircosPlot

### ISSUE THREAD

**Issue by ChakreshIITGN** [ericmjl/nxviz#376]
* nxviz version: 0.4.0
* Python version:2.7
* Operating System:Ubuntu 16.04 LTS
*Networkx version: 2.1
### Description

I am trying to colour the nodes based on an attribute 'type' in my nodes data. 

### What I Did

```
from nxviz.plots import CircosPlot as cp
c = cp(G,node_order='type',figsize = (10,10),node_color='type')
c.draw()
plt.show()

However there is no error when I use 'type' for node_order. 


NodeDataView({'RSC_2o1a': {'lat': u'28.8047', 'type': u'NRI', 'long': u'77.6823', 'afftype': u'R_C', 'label': 'RSC_2o1a'}, 'UNI_4w2u': {'lat': u'22.2994', 'type': u'SU', 'long': u'73.2081', 'afftype': u'UNI', 'label': 'UNI_4w2u'}  ### part of the node dictionary for my graph G showing the parameters

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-71-2063bccbaa5e> in <module>()
      7 print len(rem)
      8 G.remove_edges_from(edwt)
----> 9 c = cp(G,node_order='type',figsize = (10,10),node_color=str('type'))
     10 c.draw()
     11 plt.show()

/home/user1/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nxviz/plots.pyc in __init__(self, graph, **kwargs)
    458 
    459         #
--> 460         super(CircosPlot, self).__init__(graph, **kwargs)
    461 
    462     def compute_group_label_positions(self):

/home/user1/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nxviz/plots.pyc in __init__(self, graph, node_order, node_size, node_grouping, group_order, node_color, node_labels, edge_width, edge_color, data_types, nodeprops, edgeprops, node_label_color, group_label_position, group_label_color, **kwargs)
    131         if self.node_color:
    132             self.node_colors = []
--> 133             self.compute_node_colors()
    134         else:
    135             self.node_colors = ["blue"] * len(self.nodes)

/home/user1/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nxviz/plots.pyc in compute_node_colors(self)
    237             data_reduced = list(unique_everseen(data))
    238 
--> 239         dtype = infer_data_type(data)
    240         n_grps = num_discrete_groups(data)
    241 

/home/user1/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nxviz/utils.pyc in infer_data_type(data_container)
     72 
     73     else:
---> 74         raise ValueError("Not possible to tell what the data type is.")
     75 
     76 

ValueError: Not possible to tell what the data type is.

​
```

**Comment by ericmjl** [comment]
@ChakreshIITGN thanks for pinging in!

I think I could have improved the error message. nxviz tries to automatically infer the data type - ordinal, continuous, or categorical, using heuristics.

Looking through your data, I noticed you're using explicit unicode strings for everything. I'd suggest you change them all to Pythonic data types: strings (which are unicode by default), integers, and floats. That might be the bug fix, but if not, ping back and we can figure out what's going on.

Also saw that you have a lat/lon keyword attached to each node -- I'm working on a simple declarative GeoPlot that will let you get started real quick with geographic graphs. The matplotlib version already works, the altair version is still WIP. Check out the [geoplot](https://github.com/ericmjl/nxviz/tree/geoplot) branch.

**Comment by ericmjl** [comment]
Also noticed that you're using Python 2.7 - FYI I'm only explicitly supporting Python 3.6 and above :smile:.

**Comment by ChakreshIITGN** [comment]
@ericmjl   Thanks a lot for your response. Also please accept many thanks and admiration for such a wonderful package. I will make changes as per your suggestion.

**Comment by ericmjl** [comment]
Thanks a ton, @ChakreshIITGN! 

I am going to close this issue, but do feel free to reopen if there's a follow-up to this issue. If there's a separate one, please open a new ticket :smile:.
