### ISSUE TITLE
Use vega-lite as declarative, portable backend

### ISSUE THREAD

**Issue by brainstorm** [ericmjl/nxviz#445]
It would be awesome if `nxviz` had this as a (declarative) backend: https://vega.github.io/vega-lite/

**Comment by ericmjl** [comment]
@brainstorm totally agree, PRs are welcome!

**Comment by ericmjl** [comment]
As an alternative, I've been playing with Holoviews for a bit, and would love to see the declarative API backed by it too. I might be hacking on a Holoviews backend for the next iteration.
