### ISSUE TITLE
Edge width does not work with Circos plots.

### ISSUE THREAD

**Issue by sten** [ericmjl/nxviz#510]
* nxviz version: 0.5.0
* Python version: 3.5
* Operating System: Mac OS High Sierra

### Description

Thanks a lot for the very nice visualisations!

I tried several ways to set the width of the edges in a circos plot. Until I just tried the code sample that is provided in the library, which does also not work. So I guess there is some bug that got into the library. Could it be that the edge width also does not work for the arc plot? I haven't investigated this further, but I was also not able to do it there.

### What I Did

Here is the code I ran and the ouput. It's the same code as in nxviz/examples/circos/edge_width.py

<img width="717" alt="screen shot 2018-11-23 at 23 51 06" src="https://user-images.githubusercontent.com/180665/48962090-7c496200-ef7b-11e8-84c0-f9a8880d8ffe.png">

**Comment by ericmjl** [comment]
@sten, thanks for pinging in!

This reminds me that I have forgotten to cut a new release. Look out for 0.6.0 on PyPI within the next hour, and on conda-forge within the next 24 hours.

**Comment by ericmjl** [comment]
@sten, both pypi and conda forge releases are up! please install the new versions, and see if they are done right. 

Going to close this issue for the time being; feel free to re-open if there’s still something not working.

**Comment by sten** [comment]
@ericmjl Thanks a lot! Now it works!

PS: Do you know if there is a way to add labels to the axis of a matrixplot to better illustrate which nodes are ploted on each row and column?
