### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. on WinPython 3.6.6

### ISSUE THREAD

**Issue by Code4SAFrankie** [ericmjl/nxviz#531]
* nxviz version: 0.6.0
* Python version: 3.6.6
* Operating System: Windows 10

### Description

from nxviz import MatrixPlot

Running example code from 2-networkx-basics-instructor.ipynb

### What I Did

from nxviz import MatrixPlot

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

from nxviz import MatrixPlot

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-43-58f261bd60a9> in <module>()
----> 1 from nxviz import MatrixPlot
      2 
      3 m = MatrixPlot(G)
      4 m.draw()
      5 plt.show()

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz\__init__.py in <module>()
----> 1 from nxviz.plots import ArcPlot, CircosPlot, MatrixPlot, GeoPlot  # NOQA
      2 
      3 __version__ = "0.6.0"

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz\plots.py in <module>()
     15                        text_alignment)
     16 from .polcart import to_degrees
---> 17 from .utils import (cmaps, infer_data_type, is_data_diverging, items_in_groups,
     18                     n_group_colorpallet, num_discrete_groups, to_pandas_edges,
     19                     to_pandas_nodes)

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\nxviz\utils.py in <module>()
      2 
      3 import pandas as pd
----> 4 import seaborn as sns
      5 from matplotlib.colors import ListedColormap
      6 from palettable.colorbrewer import diverging, qualitative, sequential

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\rcmod.py in <module>()
      3 import functools
      4 import matplotlib as mpl
----> 5 from . import palettes, _orig_rc_params
      6 
      7 

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .colors import xkcd_rgb, crayons
     14 

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\seaborn\utils.py in <module>()
      5 
      6 import numpy as np
----> 7 from scipy import stats
      8 import pandas as pd
      9 import matplotlib as mpl

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\stats\__init__.py in <module>()
    343 from __future__ import division, print_function, absolute_import
    344 
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\stats\stats.py in <module>()
    167 from scipy._lib.six import callable, string_types
    168 from scipy._lib._version import NumpyVersion
--> 169 import scipy.special as special
    170 import scipy.linalg as linalg
    171 from . import distributions

E:\WPy-3662\python-3.6.6.amd64\lib\site-packages\scipy\special\__init__.py in <module>()
    638 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    639 
--> 640 from ._ufuncs import *
    641 
    642 from .basic import *

ImportError: DLL load failed: The specified module could not be found.

**Comment by ericmjl** [comment]
This looks to me like an installation issue with SciPy.

How did you install SciPy? Is this in a conda environment? 

If it isn't, I'm afraid I'm a bit out of my depth at this moment, as I don't have a Windows machine to play around with.

**Comment by Code4SAFrankie** [comment]
This is the WinPython distribution, not Anaconda. SciPy comes included with it, so I didn't have to install it separately.

**Comment by Code4SAFrankie** [comment]
Issue seems to already exist on SciPy.
