### ISSUE TITLE
Don't put a full list of "==" in the requirements.txt used for wheel creation

### ISSUE THREAD

**Issue by stonebig** [ericmjl/nxviz#532]
* nxviz version: 0.6.0
* Python version: 3.6.6 (WinPython64-3.6.6.2Qt5.exe)
* Operating System: Windows 10

### Description

Installing nxviz in WinPython distro causes disruption because of the exact constraints "==" imposed in nxviz wheel generates an update of the included numpy-1.15.4+MKL, and the loss of the MKL DLLs.

### What I Did

Please reduce your contraints in requirements.txt to what you  really need.

see https://github.com/winpython/winpython/issues/723
```

**Comment by ericmjl** [comment]
@stonebig thanks for reporting this. I put it in mostly because of pyup.io, which enforces exact dependencies for reproducibility and ease of debugging.

I'm a bit swamped at work at the moment. Feel free to PR in a fix on `requirements.txt`.

**Comment by stonebig** [comment]
well, pyup.io has a respectable logic. It's just non-ideal for the wheels on pypi.

**Comment by stonebig** [comment]
small question, would nxviz be able to display graphs like this one   ? https://github.com/dask/dask/blob/2c69a1c940de8c136789d5d2d054a70dfe2495dd/docs/source/graphviz.rst

**Comment by ericmjl** [comment]
I haven't put in that layout logic into nxviz. Till now, my focus has been on the viz layouts that have been already implemented here. Happy to receive a PR for graphviz-esque layouts!
