### ISSUE TITLE
polar histogram around Circos Plot

### ISSUE THREAD

**Issue by 858600** [ericmjl/nxviz#541]
* nxviz version: just downloaded
* Python version: 3.3.3 downloaded with Anaconda
* Operating System: Windows

### Description
I would like to know whether it is possible to draw a polar histogram around a Circos Plot with nxviz. I found such a graph applied only to genomics, but I think it could be a neat way to visualize one more of the nodes' metadata in any field. Also a traditional histogram below an Arc Plot would work, I suppose.

I would very much appreciate any help or suggestion (relatively new to Python here, my only knowledge comes from DataCamp courses).

**Comment by ericmjl** [comment]
Hello @858600, 

Thanks for pinging in. Adding a polar histogram, as well as more tracks, has been a common feature request, but alas, I haven't had the need for it myself, and have not had the bandwidth either. 

You are right instating that a histogram (or perhaps a more accurate alternative, a bar plot) below an ArcPlot would be an alternative. Likely, it would be two matplotlib Axes objects within one figure, such that one holds the ArcPlot, and the other holds the bar plot below, with the x-ticks on the histogram matching the x-ticks on the ArcPlot. 

If you get it working, I would love to accept your contribution to nxviz. That's what open source is all about!

Cheers,
Eric
