### ISSUE TITLE
CircosPlot of a 2-node graph plots both nodes over each other

### ISSUE THREAD

**Issue by Rabeez** [ericmjl/nxviz#544]
The `CircosPlot` does something weird when made with just two nodes. Both nodes are plotted over each other. 

```python
x = nx.Graph()
x.add_node(1)
x.add_node(2)
nxv.CircosPlot(x, node_labels=True).draw()
```
![image](https://user-images.githubusercontent.com/9392057/56061687-985f6b80-5d83-11e9-894f-a243dd0844bc.png)

The positioning is fine with 3 nodes. I'm not sure what the correct solution to this would be since a 'circular path' with just 2 nodes isn't really possible.

**Comment by ericmjl** [comment]
@Rabeez thanks for the catch! This is definitely an edge case I failed to consider when first developing the code for CircosPlots.

Technically speaking, a circular path with two nodes can mean placing them along a line, side by side, and then just drawing arcs between them. In that case, I'd suggest an ArcPlot, now that I think about it.

**Comment by Rabeez** [comment]
Yeah I thought of an ArcPlot as well. In your opinion should the user be given some sort of warning about this behaviour? Or just an outright assert `len(g.nodes)<=2` ?

**Comment by ericmjl** [comment]
> Or just an outright `assert len(g.nodes)<=2`?

I think that's definitely the right thing to do for the time being. Would you be open to another PR?

**Comment by Rabeez** [comment]
Yeah I'm working on one already for the CircosPlot labels. I'll add this change to that one. I should have it up int a few hours max.
