### ISSUE TITLE
Screenshots!

### ISSUE THREAD

**Issue by DomHudson** [ericmjl/nxviz#568]
### Description
Hi, I think it would be really useful to have screenshots on the readme. For a visualisation package this makes the first impression and saves the user installing just to see an example.

What do you think?
Many thanks,
Dom

**Comment by ericmjl** [comment]
Hi @DomHudson, yes, I'd love to see that happen! Do you have some bandwidth to submit a PR? That would be really awesome - I have to admit to needing community help on this project, as my bandwidth as become quite limited due to work.

**Comment by Rabeez** [comment]
Will be fixed in PR #580

**Comment by ericmjl** [comment]
Closing this issue because #580 is merged.
