### ISSUE TITLE
Nxivz tutorials

### ISSUE THREAD

**Issue by jphe** [ericmjl/nxviz#570]
Hi, 

I searched on google that nxviz can draw circos plot with python scripts, but I'm wondering are there any tutorials for nxviz that I can follow for step by step ?

I found one documentation https://buildmedia.readthedocs.org/media/pdf/nxviz/latest/nxviz.pdf , but it have no sample plot that for users can flow.

Can you help me how can I start my ploting with nxviz ?

Thanks,
Jphe

**Comment by ericmjl** [comment]
Hi @jphe, thanks for pinging in. Admittedly, I haven't had the time to do docs properly. That said, if you head over to https://github.com/ericmjl/Network-Analysis-Made-Simple, you'll see example plots inside those notebooks.

If you've got the bandwidth, I'd love to see your contribution to the docs! :smile:

**Comment by fding253** [comment]
Hi! If nobody’s actively working on this, mind if I take a stab at converting the Network Analysis tutorials for the “Usage” page of the docs?

**Comment by ericmjl** [comment]
@fding253 I'd love to accept that contribution from you! :smile:

**Comment by Rabeez** [comment]
Fixed in #580
