### ISSUE TITLE
Contributing Guidelines -- conda environment setup

### ISSUE THREAD

**Issue by fding253** [ericmjl/nxviz#577]
Hello!

### Description

In step 3 of the contributing guidelines, there are instructions for setting up your environment using virtualenvwrapper. I noticed there's an environment.yml file as well -- is it equivalent to use that file to set up a conda environment?

### What I Did

```
conda env create -f environment.yml
```

**Comment by Rabeez** [comment]
Yup. This works fine too

**Comment by fding253** [comment]
@Rabeez Thank you!

**Comment by ericmjl** [comment]
@fding253 would you like to make a PR to help us update the docs to work with `conda`?

**Comment by fding253** [comment]
@ericmjl Oh, just saw this! Sure, I'd be happy to update the docs with `conda` instructions!
