### ISSUE TITLE
Circosplot: Add legend indicating the label and color of each group of nodes

### ISSUE THREAD

**Issue by walter-hernandez** [ericmjl/nxviz#592]
* nxviz version:
* Python version:
* Operating System:

### Description
I worked with this library for a project that I had. One of the things that I used and that may be of benefit for other users of the library is to add to a circosplot the legend with labels and color for each group of the nodes. Attached the code below of how to do this and that you @ericmjl may like to incorporate to the library.

### What I Did

```
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import to_hex

# Get the label and color for each group used by nxviz
seen = set()
colors_group = [x for x in c.node_colors if not (x in seen or seen.add(x))] #Gets colors in RGBA
labels_group = sorted(list(set([c.graph.node[n][c.node_color] for n in c.nodes]))) #Gets group labels

# Create patchList to use as handle for plt.legend()
patchList = []
for color, label in zip(colors_group, labels_group):
    color = to_hex(color, keep_alpha=True) #Convert RGBA to HEX value
    data_key = mpatches.Patch(color=color, label=label)
    patchList.append(data_key)

# Set the labels with the custom patchList
plt.legend(handles=patchList,
           loc="lower center",
           title="Enterprise size",
           ncol=4, # 4 columns to spread the legends
           borderpad=1,
           bbox_to_anchor =(0.5, -0.05), # To move the legend box lower than the graph
           shadow=True,
           fancybox=True)
```

**Comment by ericmjl** [comment]
@walter-hernandez this looks like a wonderful piece of code! I'm wondering, would you like to submit a PR with it and thus be acknowledged as one of the contributors on the project? I'm trying to encourage more co-creation of software that we all can use. Please let me know what you think!

**Comment by walter-hernandez** [comment]
@ericmjl Sure, I can do that. Would you like to implement this feature by default when using the Circusplot or some extra input variables (the title of the legend, number of columns for labels, etc.) in the Circusplot to enable the legends?

**Comment by ericmjl** [comment]
@walter-hernandez I think enabling it by default is good first start. I'm assuming by "columns for labels", you are referring to "node attribute keys to use for labels"?

Be sure to keep the CircosPlot API declarative, so end-user only has to declare the node attribute key(s) that key the attribute labels.

Finally, a friendly reminder - if you could add an example to the example gallery (a dummy one is good enough), and post a screenshot on the PR so that I can see how it looks - that'd be much appreciated!

**Comment by walter-hernandez** [comment]
Hello @ericmjl 

Code added:

- Added the argument "group_legend" for the user to indicate if it wants the graph to include the legend or not. 
- Exposed the legend_handles in the case that the user wants to customized the legend

Included dummy examples in the directory "examples\circos"for:

- The default legend:

![circusplot_defaultlegend](https://user-images.githubusercontent.com/52283659/75636804-c78bff00-5c19-11ea-98d0-f029a1d8061d.png)


- How to customize the legend using the CircosPlot().legend_handles

![circusplot_customlegend](https://user-images.githubusercontent.com/52283659/75636749-50ef0180-5c19-11ea-859c-1487579120ae.png)

**Comment by walter-hernandez** [comment]
Since the feature has been added, I am going to close this issue
