### ISSUE TITLE
version mismatch on packages distributed by conda and pypi

### ISSUE THREAD

**Issue by kdpenner** [ericmjl/nxviz#664]
* nxviz version: theoretically 0.6.3
* Python version: 3.9
* Operating System: macOS

### Description

conda and pypi install "0.6.3" but the packages are missing much of the functionality in the 0.6.3 package hosted on github. Missing annotate.py, etc.

```
(nxviz) kpenner@Redoublement ~ % conda list nxviz
# packages in environment at /Users/kpenner/miniconda3/envs/nxviz:
#
# Name                    Version                   Build  Channel
nxviz                     0.6.3            py39h6e9494a_0    conda-forge
```

```
(nxviz) kpenner@Redoublement nxviz % pwd
/Users/kpenner/miniconda3/envs/nxviz/lib/python3.9/site-packages/nxviz
(nxviz) kpenner@Redoublement nxviz % ls
__init__.py	geometry.py	plots.py	utils.py
__pycache__	io.py		polcart.py
```

**Comment by ericmjl** [comment]
@kdpenner yes, thank you for the ping! 

I had a change in jobs, and it dropped from my mind to cut a new release. Hang tight!

**Comment by ericmjl** [comment]
@kdpenner I just cut a new release. Please check it out on PyPI. As of 1 pm EST, the bots on conda-forge should be at work to make it available on conda-forge as well!

**Comment by kdpenner** [comment]
Worked for me, thanks.
