### ISSUE TITLE
Having trouble re-creating graph

### ISSUE THREAD

**Issue by noobiecxy** [ericmjl/nxviz#667]
Professor left us an assignment on re-creating the attached graph, However, I'm still kinda clueless of how to build the data frame and draw what kind of the graph. Please if anyone knows how to create similar graph can contact me, I'm willing to pay you handsomely.  Thanks
![est 1](https://user-images.githubusercontent.com/88362180/128630678-f3d93fe4-d21f-4477-8a1e-5648ba409cc2.jpeg)

**Comment by ericmjl** [comment]
Hi @noobiecxy, thanks for chiming in. Unfortunately, I don't think I have the bandwidth to help you here. The issue tracker is intended for reporting bugs in the library. I would suggest you try a different medium for homework help.
