### ISSUE TITLE
Feature Request: Node label layout for circus plot

### ISSUE THREAD

**Issue by alirezatheh** [ericmjl/nxviz#674]
Hi @ericmjl, in the old API there was a very cool feature for circus plot called `node_label_layout`. It had three options: `numbers`, `rotation`, `standard`. Do you have any plan to add that to the new API?

**Comment by ericmjl** [comment]
Yes! That sounds like a good feature to bring back. I'm wondering if there's a way to leverage the new code infra that we have to do node _label_ layouts that are sane defaults for all types of plots? 

This is also a good time to think carefully about where to place the function that would be akin to `node_label_layout`. Is this an _annotation_ of some kind? I think it is, and would be best placed in `annotate.py`. What do you think?

**Comment by AlirezaTheH** [comment]
Yes, I also think `annotate.py` is best place to do this. There are already node labels functions there and I also think implementations will be something similar to group annotation. And defaults could what we have now, labels in center of nodes.
