### ISSUE TITLE
importing nxviz fails in python 2.7

### ISSUE THREAD

**Issue by andins** [ericmjl/nxviz#73]
* nxviz version:
* Python version: 2.7
* Operating System: Ubuntu 16.04

### Description

I installed nxviz as sudo pip install nxviz (no error)
but when I try to import it in IPython it says:

In 1 : import nxviz as nv
File "/usr/local/lib/python2.7/dist-packages/nxviz/plots.py", line 232
patch = patches.PathPatch(path, lw=1, **self.edgeprops, zorder=1)
^
SyntaxError: invalid syntax

### What I Did

In Python 3 the issue does not appear

**Comment by WMGoBuffs** [comment]
Seeing a similar issue, Python 2.7, installed version 0.3.1 from pip

**Comment by ericmjl** [comment]
Thanks for leaving a comment on this. The API is designed to be Py3K compatible only, as it takes advantage of some new language features in Python 3.
