### ISSUE TITLE
Node color issues - accent errors

### ISSUE THREAD

**Issue by patriciata** [ericmjl/nxviz#76]
* nxviz version: 0.3.1
* Python version: 3.6

### Description

Attempt to add colour to Arcmap fails

### What I Did

Invalid Accent colormap errors result when running ArcPlot(M, node_color='Category', node_order='degree') on more than a certain number of categories.

**Comment by ericmjl** [comment]
Thanks @patriciata! I will be sure to document this in the code.

**Comment by ericmjl** [comment]
@patriciata FYI docs are built, would love feedback!
